name: 'C++ CI'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-program-options-dev libboost-system-dev libboost-filesystem-dev -y
      - run: sudo apt-get install nlohmann-json3-dev -y
      - run: sudo apt-get install libtinyxml2-dev libxml2-dev -y
      - run: sudo apt-get install libyaml-cpp-dev -y          

      - run: sudo apt-get install libboost-all-dev -y # Ensures Boost libraries are available
      - run: sudo apt-get install libssl-dev -y  # Ensure OpenSSL is statically linked

      - run: mkdir -p build
      # - run: cmake -B build -S . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON
      - run: cmake -B build -S . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON -DYAML_CPP_STATIC=ON

      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
      - run: cmake --build build --target package
      - run: ls -lh build/*.deb
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/validator-0.0.${{ github.run_number }}-Linux.deb
          asset_name: validator-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package